# Header
menu:
  é¦–é¡µ: /
  å…³äº: /about

# ä¸»é¡µbannerå›¾
banner: https://img.paulzzh.tech/touhou/konachan/image/29311ce4558348e2a1121ff6889944f9.jpg

# ç«™ç‚¹é€šçŸ¥ä¿¡æ¯
notice: å“Ÿå˜¿ã€‚æ²¡äº‹æ”¶è—æ”¶è—ï¼Œè¯•è¯•(é€ä¸–)ï¼Ÿ

# ä½œè€…ä¿¡æ¯
author:
  name: 4cDVujM6
  avatar: https://i.loli.net/2021/08/22/npK1gsXyzDOwV3e.jpg
  description: å“‡å¡ï¼Œå¥½å±‘çš„ç‹—å•ŠğŸ•ğŸ¾

toc:
  max_depth: 3 # ç”Ÿæˆ TOC çš„æœ€å¤§æ·±åº¦
  min_depth: 2 # ç”Ÿæˆ TOC çš„æœ€å°æ·±åº¦

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine è¯„è®º
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # è¿™é‡ŒappIdå’ŒappKeyä¸€å®šä¸€å®šè¦æ”¹æˆè‡ªå·±çš„ï¼Œæ²¡æœ‰çš„è¯å»https://leancloud.cnè¿™ä¸ªç½‘ç«™æ³¨å†Œåˆ›å»ºä¸€ä¸ª
  valine:
    appId: 
    appKey: 
    avatar: mm
    placeholder: éšä¾¿è¯´ç‚¹ä»€ä¹ˆå­ï½
    notify: true
    visitor: true
    pageSize: 10
  # disqus è¯„è®º
  # docs: https://disqus.com/
  disqus:
    website: 
    error: å¦‚æœä½ çœ‹ä¸åˆ°è¯„è®ºï¼Œé‚£ä¹ˆå°±çœŸçš„çœ‹ä¸åˆ°è¯„è®º w(ã‚œĞ”ã‚œ)w

# dplayer è§†é¢‘æ’­æ”¾
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer éŸ³é¢‘æ’­æ”¾
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# å›½å†…å¤‡æ¡ˆä¿¡æ¯
beian: 

# è°·æ­Œåˆ†æ
google_analytics: 
# gaugesåˆ†æ
gauges_analytics: 
# ç™¾åº¦åˆ†æ
baidu_analytics: 
# è…¾è®¯åˆ†æ
tencent_analytics: 
# ç«™ç‚¹ico
favicon: https://i.loli.net/2021/08/22/npK1gsXyzDOwV3e.jpg


# Social Icon
social_icon:
  enable: false
  icons:
    ins     :
    zhihu   :
    weibo   : 
    github  : 
    twitter : 
